require("__Atomic_Overhaul__/lib/core")

require("prototypes/group")
require(fluids .. "waste-solution")
require(items .. "empty-fuel-cell")
require(items .. "graphite-depleted-cell")
require(items .. "graphite-fuel-cell")
require(items .. "graphite")
require(items .. "MOX-depleted-cell")
require(items .. "MOX-fuel-cell")
require(items .. "MOX")
require(items .. "nuclear-waste")
require(items .. "plutonium-depleted-cell")
require(items .. "plutonium-fuel-cell")
require(items .. "plutonium-fuel")
require(items .. "plutonium")
require(items .. "research-data")
require(items .. "thorium-depleted-cell")
require(items .. "thorium-fuel-cell")
require(items .. "thorium-module-1")
require(items .. "thorium-module-2")
require(items .. "thorium-module-3")
require(items .. "thorium")
require(recipes .. "empty-fuel-cell-recipe")
require(recipes .. "graphite-fuel-cell-recipe")
require(recipes .. "graphite-fuel-cell-recipe")
require(recipes .. "graphite-fuel-reprocessing")
require(recipes .. "graphite-recipe")
require(recipes .. "MOX-fuel-cell-recipe")
require(recipes .. "MOX-fuel-reprocessing")
require(recipes .. "MOX-recipe")
require(recipes .. "MOX-without-research-data")
require(recipes .. "plutonium-fuel-cell-recipe")
require(recipes .. "plutonium-fuel-recipe")
require(recipes .. "plutonium-fuel-reprocessing")
require(recipes .. "plutonium-without-research-data")
require(recipes .. "research-data")
require(recipes .. "thorium-fuel-cell-recipe")
require(recipes .. "thorium-fuel-reprocessing")
require(recipes .. "thorium-module-1")
require(recipes .. "thorium-module-2")
require(recipes .. "thorium-module-3")
require(recipes .. "thorium-recipe")
require(recipes .. "uranium-without-research-data")
require(recipes .. "waste-liquefaction")
require(recipes .. "waste-solution-reprocessing")
require(techs .. "graphite-fuel-reprocessing")
require(techs .. "graphite-processing")
require(techs .. "plutonium-fuel-reprocessing")
require(techs .. "plutonium-fuel")
require(techs .. "plutonium-processing")
require(techs .. "plutonium-without-research-data")
require(techs .. "MOX-fuel-reprocessing")
require(techs .. "MOX-processing")
require(techs .. "MOX-without-research-data")
require(techs .. "thorium-fuel-reprocessing")
require(techs .. "thorium-module-1")
require(techs .. "thorium-module-2")
require(techs .. "thorium-module-3")
require(techs .. "thorium-processing")
require(techs .. "uranium-without-research-data")
require(techs .. "waste-reprocessing")


--Addon stage begins here.
if mods["space-exploration"] and settings.startup["se-addon"].value == true then
    require("__Atomic_Overhaul__/lib/se-addon")
        require("prototypes.addons.space-exploration.group")
        require(se_addon_items .. "advanced-fuel-cell")
        require(se_addon_items .. "beryllium-7")
        require(se_addon_items .. "holmium-166")
        require(se_addon_items .. "iridium-192")
        require(se_addon_items .. "iridium-fuel-cell")
        require(se_addon_items .. "iridium-depleted-cell")
        require(se_addon_items .. "holmium-fuel-cell")
        require(se_addon_items .. "holmium-depleted-cell")
        require(se_addon_items .. "beryllium-fuel-cell")
        require(se_addon_items .. "beryllium-depleted-cell")

        require(se_addon_recipes .. "advanced-fuel-cell-recipe")
        require(se_addon_recipes .. "iridium-fuel-cell-recipe")
        require(se_addon_recipes .. "holmium-fuel-cell-recipe")
        require(se_addon_recipes .. "beryllium-fuel-cell-recipe")
        require(se_addon_recipes .. "iridium-192-recipe")
        require(se_addon_recipes .. "holmium-166-recipe")
        require(se_addon_recipes .. "beryllium-7-recipe")

        require(se_addon_techs .. "iridium-192-processing")
        require(se_addon_techs .. "holmium-166-processing")
        require(se_addon_techs .. "beryllium-7-processing")
        if not mods["RealisticReactors"] then
        require(se_addon_entities .."space-reactor")
        else
        require(se_addon_entities .."space-reactor-rr")
        end


        if ao_debug == true then
            log(debug_addon_text .. "space-exploration")
        end
end