local items = "prototypes.items."
local recipes = "prototypes.recipes."
local techs = "prototypes.technologies."
local vanilla = "prototypes.vanilla-changes."
graphics = "__Atomic_Overhaul__/graphics/icons/"

require("prototypes/group")
require(items .. "empty-fuel-cell")
require(items .. "graphite")
require(items .. "graphite-depleted-cell")
require(items .. "graphite-fuel-cell")
require(items .. "MOX")
require(items .. "MOX-depleted-cell")
require(items .. "MOX-fuel-cell")
require(items .. "nuclear-waste")
require(items .. "plutonium")
require(items .. "plutonium-depleted-cell")
require(items .. "plutonium-fuel")
require(items .. "plutonium-fuel-cell")
require(items .. "research-data")
require(items .. "thorium")
require(items .. "thorium-depleted-cell")
require(items .. "thorium-fuel-cell")
require(recipes .. "empty-fuel-cell-recipe")
require(recipes .. "graphite-fuel-cell-recipe")
require(recipes .. "graphite-fuel-reprocessing")
require(recipes .. "plutonium-fuel-recipe")
require(recipes .. "plutonium-fuel-cell-recipe")
require(recipes .. "plutonium-fuel-reprocessing")
require(recipes .. "thorium-fuel-cell-recipe")
require(recipes .. "MOX-fuel-cell-recipe")
require(recipes .. "MOX-recipe")
require(recipes .. "graphite-fuel-cell-recipe")
require(recipes .. "graphite-recipe")
require(recipes .. "thorium-recipe")
require(techs .. "thorium-processing")
require(techs .. "graphite-fuel-reprocessing")
require(techs .. "graphite-processing")
require(techs .. "plutonium-fuel")
require(techs .. "plutonium-processing")
require(techs .. "plutonium-fuel-reprocessing")
require(vanilla .. "recipes")
require(vanilla .. "technologies")
require(vanilla .. "uranium-fuel-cell")
