script.on_init(function() --I will make this more compact in the future
    if remote.interfaces["kr-radioactivity"] then
        remote.call("kr-radioactivity", "add_item", "MOX")
        remote.call("kr-radioactivity", "add_item", "MOX-depleted-cell")
        remote.call("kr-radioactivity", "add_item", "MOX-fuel-cell")
        remote.call("kr-radioactivity", "add_item", "MOX-fuel-rod")
        remote.call("kr-radioactivity", "add_item", "plutonium")
        remote.call("kr-radioactivity", "add_item", "plutonium-depleted-cell")
        remote.call("kr-radioactivity", "add_item", "plutonium-fuel")
        remote.call("kr-radioactivity", "add_item", "plutonium-fuel-cell")
        remote.call("kr-radioactivity", "add_item", "plutonium-fuel-rod")
        remote.call("kr-radioactivity", "add_item", "thorium")
        remote.call("kr-radioactivity", "add_item", "thorium-depleted-cell")
        remote.call("kr-radioactivity", "add_item", "thorium-fuel-cell")
        remote.call("kr-radioactivity", "add_item", "thorium-fuel-rod")
        remote.call("kr-radioactivity", "add_item", "uranium-fuel-rod")
        if settings.startup["se-addon"].value == true and game.active_mods["space-exploration"] then
            remote.call("kr-radioactivity", "add_item", "advanced-MOX-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-MOX-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-plutonium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-plutonium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-thorium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-thorium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-uranium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-uranium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "beryllium-7")
            remote.call("kr-radioactivity", "add_item", "beryllium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "beryllium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "beryllium-fuel-rod")
            remote.call("kr-radioactivity", "add_item", "holmium-166")
            remote.call("kr-radioactivity", "add_item", "holmium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "holmium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "holmium-fuel-rod")
            remote.call("kr-radioactivity", "add_item", "iridium-192")
            remote.call("kr-radioactivity", "add_item", "iridium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "iridium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "iridium-fuel-rod")
        end
    end
    FixUraniumResources()
end)
script.on_configuration_changed(function()
    if remote.interfaces["kr-radioactivity"] then
        remote.call("kr-radioactivity", "add_item", "MOX")
        remote.call("kr-radioactivity", "add_item", "MOX-depleted-cell")
        remote.call("kr-radioactivity", "add_item", "MOX-fuel-cell")
        remote.call("kr-radioactivity", "add_item", "MOX-fuel-rod")
        remote.call("kr-radioactivity", "add_item", "plutonium")
        remote.call("kr-radioactivity", "add_item", "plutonium-depleted-cell")
        remote.call("kr-radioactivity", "add_item", "plutonium-fuel")
        remote.call("kr-radioactivity", "add_item", "plutonium-fuel-cell")
        remote.call("kr-radioactivity", "add_item", "plutonium-fuel-rod")
        remote.call("kr-radioactivity", "add_item", "thorium")
        remote.call("kr-radioactivity", "add_item", "thorium-depleted-cell")
        remote.call("kr-radioactivity", "add_item", "thorium-fuel-cell")
        remote.call("kr-radioactivity", "add_item", "thorium-fuel-rod")
        remote.call("kr-radioactivity", "add_item", "uranium-fuel-rod")
        if settings.startup["se-addon"].value == true and game.active_mods["space-exploration"] then
            remote.call("kr-radioactivity", "add_item", "advanced-MOX-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-MOX-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-plutonium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-plutonium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-thorium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-thorium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-uranium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "advanced-uranium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "beryllium-7")
            remote.call("kr-radioactivity", "add_item", "beryllium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "beryllium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "beryllium-fuel-rod")
            remote.call("kr-radioactivity", "add_item", "holmium-166")
            remote.call("kr-radioactivity", "add_item", "holmium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "holmium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "holmium-fuel-rod")
            remote.call("kr-radioactivity", "add_item", "iridium-192")
            remote.call("kr-radioactivity", "add_item", "iridium-depleted-cell")
            remote.call("kr-radioactivity", "add_item", "iridium-fuel-cell")
            remote.call("kr-radioactivity", "add_item", "iridium-fuel-rod")
        end
    end
end)
