return
{
  entities =
  {
    {"nuclear-reactor", {x = -0.5, y = -2.5}, {dmg = {dmg = 380}, }},
    {"iron-chest", {x = -4.5, y = -0.5}, {dmg = {dmg = 19}, items = {["non-moderated-fuel-cell"] = 3}, }},
    {"small-electric-pole", {x = 2.5, y = -1.5}, {}},
    {"inserter", {x = 2.5, y = -0.5}, {dir = "west", }},
    {"iron-chest", {x = 3.5, y = -0.5}, {items = {["non-moderated-depleted-cell"] = 6}, }},
    {"small-electric-pole", {x = -3.5, y = 1.5}, {}},
    {"inserter", {x = -4.5, y = 0.5}, {dir = "south", dmg = {dmg = 19}, }},
    {"fast-transport-belt", {x = -4.5, y = 1.5}, {}},
    {"heat-furnace", {x = -2, y = 1}, {dmg = {dmg = 133}, }},
    {"heat-furnace", {x = 0, y = 1}, {dmg = {dmg = 152}, }},
    {"inserter-remnants", {x = 3.5, y = 0.5}, {}},
    {"fast-transport-belt", {x = 3.5, y = 1.5}, {dir = "south", }},
    {"fast-transport-belt", {x = -6.5, y = 3.5}, {dir = "east", dmg = {dmg = 19}, }},
    {"fast-transport-belt", {x = -5.5, y = 3.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -5.5, y = 2.5}, {dir = "east", dmg = {dmg = 38}, }},
    {"fast-transport-belt", {x = -6.5, y = 2.5}, {dir = "east", dmg = {dmg = 38}, }},
    {"fast-transport-belt-remnants", {x = -4.5, y = 2.5}, {}},
    {"fast-transport-belt", {x = -4.5, y = 3.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -3.5, y = 3.5}, {dir = "east", }},
    {"fast-transport-belt-remnants", {x = -1.5, y = 3.5}, {dir = "east", }},
    {"inserter-remnants", {x = -1.5, y = 2.5}, {}},
    {"fast-transport-belt", {x = -2.5, y = 3.5}, {dir = "east", dmg = {dmg = 114}, }},
    {"long-handed-inserter", {x = -2.5, y = 2.5}, {dir = "south", }},
    {"fast-transport-belt", {x = 0.5, y = 3.5}, {dir = "east", dmg = {dmg = 38}, }},
    {"fast-transport-belt", {x = -0.5, y = 3.5}, {dir = "east", dmg = {dmg = 57}, }},
    {"long-handed-inserter", {x = -0.5, y = 2.5}, {dir = "south", }},
    {"inserter", {x = 0.5, y = 2.5}, {dmg = {dmg = 133}, }},
    {"fast-transport-belt", {x = 2.5, y = 3.5}, {dir = "east", dmg = {dmg = 19}, }},
    {"fast-transport-belt", {x = 1.5, y = 3.5}, {dir = "east", dmg = {dmg = 19}, }},
    {"inserter", {x = 2.5, y = 2.5}, {dmg = {dmg = 76}, }},
    {"fast-transport-belt", {x = 4.5, y = 2.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 3.5, y = 2.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 4.5, y = 3.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 3.5, y = 3.5}, {dir = "east", dmg = {dmg = 76}, }},
    {"iron-chest", {x = 6.5, y = 3.5}, {dmg = {dmg = 114}, items = {["iron-plate"] = 22}, }},
    {"inserter", {x = 5.5, y = 3.5}, {dir = "west", dmg = {dmg = 57}, }},
    {"fast-transport-belt-remnants", {x = -6.5, y = 4.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -5.5, y = 4.5}, {dir = "east", dmg = {dmg = 21}, }},
    {"fast-transport-belt", {x = -3.5, y = 4.5}, {dir = "east", dmg = {dmg = 19}, }},
    {"fast-transport-belt", {x = -4.5, y = 4.5}, {dir = "east", dmg = {dmg = 57}, }},
    {"fast-transport-belt-remnants", {x = -1.5, y = 4.5}, {dir = "east", }},
    {"fast-transport-belt", {x = -2.5, y = 4.5}, {dir = "east", dmg = {dmg = 19}, }},
    {"fast-transport-belt-remnants", {x = -0.5, y = 4.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 0.5, y = 4.5}, {dir = "east", dmg = {dmg = 133}, }},
    {"fast-transport-belt-remnants", {x = 2.5, y = 4.5}, {dir = "east", }},
    {"fast-transport-belt", {x = 1.5, y = 4.5}, {dir = "east", dmg = {dmg = 19}, }},
    {"small-electric-pole", {x = 5.5, y = 4.5}, {}},
  },
  tiles =
  {
    {"grass-1", {x = -8, y = -6}},
    {"grass-1", {x = -8, y = -5}},
    {"grass-1", {x = -8, y = -4}},
    {"grass-1", {x = -8, y = -3}},
    {"grass-1", {x = -8, y = -2}},
    {"grass-1", {x = -8, y = -1}},
    {"grass-1", {x = -8, y = 0}},
    {"grass-1", {x = -8, y = 1}},
    {"grass-1", {x = -8, y = 2}},
    {"grass-1", {x = -8, y = 3}},
    {"grass-1", {x = -8, y = 4}},
    {"grass-1", {x = -8, y = 5}},
    {"grass-1", {x = -7, y = -6}},
    {"grass-1", {x = -7, y = -5}},
    {"grass-1", {x = -7, y = -4}},
    {"grass-1", {x = -7, y = -3}},
    {"grass-1", {x = -7, y = -2}},
    {"grass-1", {x = -7, y = -1}},
    {"grass-1", {x = -7, y = 0}},
    {"grass-1", {x = -7, y = 1}},
    {"grass-1", {x = -7, y = 2}},
    {"grass-1", {x = -7, y = 3}},
    {"grass-1", {x = -7, y = 4}},
    {"grass-1", {x = -7, y = 5}},
    {"grass-1", {x = -6, y = -6}},
    {"grass-1", {x = -6, y = -5}},
    {"grass-1", {x = -6, y = -4}},
    {"grass-1", {x = -6, y = -3}},
    {"grass-1", {x = -6, y = -2}},
    {"grass-1", {x = -6, y = -1}},
    {"grass-1", {x = -6, y = 0}},
    {"grass-1", {x = -6, y = 1}},
    {"grass-1", {x = -6, y = 2}},
    {"grass-1", {x = -6, y = 3}},
    {"grass-1", {x = -6, y = 4}},
    {"grass-1", {x = -6, y = 5}},
    {"grass-1", {x = -5, y = -6}},
    {"grass-1", {x = -5, y = -5}},
    {"grass-1", {x = -5, y = -4}},
    {"grass-1", {x = -5, y = -3}},
    {"grass-1", {x = -5, y = -2}},
    {"grass-1", {x = -5, y = -1}},
    {"grass-1", {x = -5, y = 0}},
    {"grass-1", {x = -5, y = 1}},
    {"grass-1", {x = -5, y = 2}},
    {"grass-1", {x = -5, y = 3}},
    {"grass-1", {x = -5, y = 4}},
    {"grass-1", {x = -5, y = 5}},
    {"grass-1", {x = -4, y = -6}},
    {"grass-1", {x = -4, y = -5}},
    {"grass-1", {x = -4, y = -4}},
    {"grass-1", {x = -4, y = -3}},
    {"grass-1", {x = -4, y = -2}},
    {"grass-1", {x = -4, y = -1}},
    {"grass-1", {x = -4, y = 0}},
    {"grass-1", {x = -4, y = 1}},
    {"grass-1", {x = -4, y = 2}},
    {"grass-1", {x = -4, y = 3}},
    {"grass-1", {x = -4, y = 4}},
    {"grass-1", {x = -4, y = 5}},
    {"grass-1", {x = -3, y = -6}},
    {"grass-1", {x = -3, y = -5}},
    {"grass-1", {x = -3, y = -4}},
    {"grass-1", {x = -3, y = -3}},
    {"grass-1", {x = -3, y = -2}},
    {"grass-1", {x = -3, y = -1}},
    {"grass-1", {x = -3, y = 0}},
    {"grass-1", {x = -3, y = 1}},
    {"grass-1", {x = -3, y = 2}},
    {"grass-1", {x = -3, y = 3}},
    {"grass-1", {x = -3, y = 4}},
    {"grass-1", {x = -3, y = 5}},
    {"grass-1", {x = -2, y = -6}},
    {"grass-1", {x = -2, y = -5}},
    {"grass-1", {x = -2, y = -4}},
    {"grass-1", {x = -2, y = -3}},
    {"grass-1", {x = -2, y = -2}},
    {"grass-1", {x = -2, y = -1}},
    {"grass-1", {x = -2, y = 0}},
    {"grass-1", {x = -2, y = 1}},
    {"grass-1", {x = -2, y = 2}},
    {"grass-1", {x = -2, y = 3}},
    {"grass-1", {x = -2, y = 4}},
    {"grass-1", {x = -2, y = 5}},
    {"grass-1", {x = -1, y = -6}},
    {"grass-1", {x = -1, y = -5}},
    {"grass-1", {x = -1, y = -4}},
    {"grass-1", {x = -1, y = -3}},
    {"grass-1", {x = -1, y = -2}},
    {"grass-1", {x = -1, y = -1}},
    {"grass-1", {x = -1, y = 0}},
    {"grass-1", {x = -1, y = 1}},
    {"grass-1", {x = -1, y = 2}},
    {"grass-1", {x = -1, y = 3}},
    {"grass-1", {x = -1, y = 4}},
    {"grass-1", {x = -1, y = 5}},
    {"grass-1", {x = 0, y = -6}},
    {"grass-1", {x = 0, y = -5}},
    {"grass-1", {x = 0, y = -4}},
    {"grass-1", {x = 0, y = -3}},
    {"grass-1", {x = 0, y = -2}},
    {"grass-1", {x = 0, y = -1}},
    {"grass-1", {x = 0, y = 0}},
    {"grass-1", {x = 0, y = 1}},
    {"grass-1", {x = 0, y = 2}},
    {"grass-1", {x = 0, y = 3}},
    {"grass-1", {x = 0, y = 4}},
    {"grass-1", {x = 0, y = 5}},
    {"grass-1", {x = 1, y = -6}},
    {"grass-1", {x = 1, y = -5}},
    {"grass-1", {x = 1, y = -4}},
    {"grass-1", {x = 1, y = -3}},
    {"grass-1", {x = 1, y = -2}},
    {"grass-1", {x = 1, y = -1}},
    {"grass-1", {x = 1, y = 0}},
    {"grass-1", {x = 1, y = 1}},
    {"grass-1", {x = 1, y = 2}},
    {"grass-1", {x = 1, y = 3}},
    {"grass-1", {x = 1, y = 4}},
    {"grass-1", {x = 1, y = 5}},
    {"grass-1", {x = 2, y = -6}},
    {"grass-1", {x = 2, y = -5}},
    {"grass-1", {x = 2, y = -4}},
    {"grass-1", {x = 2, y = -3}},
    {"grass-1", {x = 2, y = -2}},
    {"grass-1", {x = 2, y = -1}},
    {"grass-1", {x = 2, y = 0}},
    {"grass-1", {x = 2, y = 1}},
    {"grass-1", {x = 2, y = 2}},
    {"grass-1", {x = 2, y = 3}},
    {"grass-1", {x = 2, y = 4}},
    {"grass-1", {x = 2, y = 5}},
    {"grass-1", {x = 3, y = -6}},
    {"grass-1", {x = 3, y = -5}},
    {"grass-1", {x = 3, y = -4}},
    {"grass-1", {x = 3, y = -3}},
    {"grass-1", {x = 3, y = -2}},
    {"grass-1", {x = 3, y = -1}},
    {"grass-1", {x = 3, y = 0}},
    {"grass-1", {x = 3, y = 1}},
    {"grass-1", {x = 3, y = 2}},
    {"grass-1", {x = 3, y = 3}},
    {"grass-1", {x = 3, y = 4}},
    {"grass-1", {x = 3, y = 5}},
    {"grass-1", {x = 4, y = -6}},
    {"grass-1", {x = 4, y = -5}},
    {"grass-1", {x = 4, y = -4}},
    {"grass-1", {x = 4, y = -3}},
    {"grass-1", {x = 4, y = -2}},
    {"grass-1", {x = 4, y = -1}},
    {"grass-1", {x = 4, y = 0}},
    {"grass-1", {x = 4, y = 1}},
    {"grass-1", {x = 4, y = 2}},
    {"grass-1", {x = 4, y = 3}},
    {"grass-1", {x = 4, y = 4}},
    {"grass-1", {x = 4, y = 5}},
    {"grass-1", {x = 5, y = -6}},
    {"grass-1", {x = 5, y = -5}},
    {"grass-1", {x = 5, y = -4}},
    {"grass-1", {x = 5, y = -3}},
    {"grass-1", {x = 5, y = -2}},
    {"grass-1", {x = 5, y = -1}},
    {"grass-1", {x = 5, y = 0}},
    {"grass-1", {x = 5, y = 1}},
    {"grass-1", {x = 5, y = 2}},
    {"grass-1", {x = 5, y = 3}},
    {"grass-1", {x = 5, y = 4}},
    {"grass-1", {x = 5, y = 5}},
    {"grass-1", {x = 6, y = -6}},
    {"grass-1", {x = 6, y = -5}},
    {"grass-1", {x = 6, y = -4}},
    {"grass-1", {x = 6, y = -3}},
    {"grass-1", {x = 6, y = -2}},
    {"grass-1", {x = 6, y = -1}},
    {"grass-1", {x = 6, y = 0}},
    {"grass-1", {x = 6, y = 1}},
    {"grass-1", {x = 6, y = 2}},
    {"grass-1", {x = 6, y = 3}},
    {"grass-1", {x = 6, y = 4}},
    {"grass-1", {x = 6, y = 5}},
    {"grass-1", {x = 7, y = -6}},
    {"grass-1", {x = 7, y = -5}},
    {"grass-1", {x = 7, y = -4}},
    {"grass-1", {x = 7, y = -3}},
    {"grass-1", {x = 7, y = -2}},
    {"grass-1", {x = 7, y = -1}},
    {"grass-1", {x = 7, y = 0}},
    {"grass-1", {x = 7, y = 1}},
    {"grass-1", {x = 7, y = 2}},
    {"grass-1", {x = 7, y = 3}},
    {"grass-1", {x = 7, y = 4}},
    {"grass-1", {x = 7, y = 5}},
  }
}
