return
{
  entities =
  {
    {"item-on-ground", {x = -5.55, y = -4.04}, {}},
    {"fast-transport-belt", {x = -5.5, y = -3}, {dir = "south", dmg = {dmg = 57}, }},
    {"fast-transport-belt", {x = -4.5, y = -4}, {}},
    {"fast-transport-belt", {x = -4.5, y = -3}, {dmg = {dmg = 19}, }},
    {"centrifuge", {x = -1.5, y = -3}, {dmg = {dmg = 303}, recipe = "research-data-recipe", }},
    {"item-on-ground", {x = -5.26, y = -1.49}, {}},
    {"fast-transport-belt-remnants", {x = -5.5, y = -1}, {}},
    {"fast-transport-belt", {x = -5.5, y = -2}, {dir = "south", dmg = {dmg = 19}, }},
    {"item-on-ground", {x = -4.27, y = -1.51}, {}},
    {"fast-transport-belt-remnants", {x = -4.5, y = -2}, {dir = "south", }},
    {"long-handed-inserter", {x = -3.5, y = -1}, {dir = "west", }},
    {"inserter", {x = -3.5, y = -2}, {dir = "west", }},
    {"fast-transport-belt", {x = -4.5, y = -1}, {dmg = {dmg = 19}, }},
    {"inserter", {x = 0.5, y = -2}, {dir = "west", }},
    {"fast-transport-belt-remnants", {x = 1.5, y = -1}, {dir = "south", }},
    {"fast-transport-belt", {x = 1.5, y = -2}, {dir = "south", dmg = {dmg = 95}, }},
    {"lab", {x = 4.5, y = 0}, {dmg = {dmg = 62}, }},
    {"fast-transport-belt", {x = -5.5, y = 1}, {dir = "south", dmg = {dmg = 95}, }},
    {"fast-transport-belt", {x = -5.5, y = 0}, {dir = "south", dmg = {dmg = 76}, }},
    {"item-on-ground", {x = -4.27, y = 1.25}, {}},
    {"item-on-ground", {x = -4.27, y = 1.49}, {}},
    {"fast-transport-belt-remnants", {x = -4.5, y = 1}, {dir = "south", }},
    {"inserter", {x = -3.5, y = 1}, {dir = "west", }},
    {"fast-transport-belt", {x = -4.5, y = 0}, {dmg = {dmg = 38}, }},
    {"centrifuge-remnants", {x = -1.5, y = 0}, {}},
    {"inserter", {x = 0.5, y = 0}, {dir = "west", }},
    {"item-on-ground", {x = 1.78, y = 0.23}, {}},
    {"item-on-ground", {x = 1.99, y = 0.23}, {}},
    {"item-on-ground", {x = 1.26, y = -0.23}, {}},
    {"item-on-ground", {x = 1.5, y = -0.23}, {}},
    {"item-on-ground", {x = 1.75, y = -0.23}, {}},
    {"item-on-ground", {x = 1.99, y = -0.23}, {}},
    {"fast-transport-belt-remnants", {x = 1.5, y = 0}, {dir = "east", }},
    {"inserter", {x = 2.5, y = 0}, {dir = "west", dmg = {dmg = 104}, }},
    {"fast-transport-belt", {x = 1.5, y = 1}, {dmg = {dmg = 114}, }},
    {"item-on-ground", {x = -5.26, y = 2.51}, {}},
    {"item-on-ground", {x = -5.73, y = 2.51}, {}},
    {"fast-transport-belt-remnants", {x = -5.5, y = 3}, {}},
    {"fast-transport-belt", {x = -5.5, y = 2}, {dir = "south", }},
    {"long-handed-inserter", {x = -3.5, y = 2}, {dir = "west", }},
    {"fast-transport-belt", {x = -4.5, y = 2}, {dmg = {dmg = 19}, }},
    {"fast-transport-belt", {x = -4.5, y = 3}, {dmg = {dmg = 38}, }},
    {"centrifuge", {x = -1.5, y = 3}, {dmg = {dmg = 170}, recipe = "research-data-recipe", }},
    {"inserter", {x = 0.5, y = 2}, {dir = "west", }},
    {"fast-transport-belt", {x = 1.5, y = 2}, {dmg = {dmg = 57}, }},
    {"item-on-ground", {x = -4.91, y = 4.88}, {}},
    {"fast-transport-belt", {x = -5.5, y = 4}, {dir = "south", }},
    {"fast-transport-belt", {x = -4.5, y = 4}, {dmg = {dmg = 19}, }},
  },
  tiles =
  {
    {"grass-1", {x = -7, y = -5.5}},
    {"grass-1", {x = -7, y = -4.5}},
    {"grass-1", {x = -7, y = -3.5}},
    {"grass-1", {x = -7, y = -2.5}},
    {"grass-1", {x = -7, y = -1.5}},
    {"grass-1", {x = -7, y = -0.5}},
    {"grass-1", {x = -7, y = 0.5}},
    {"grass-1", {x = -7, y = 1.5}},
    {"grass-1", {x = -7, y = 2.5}},
    {"grass-1", {x = -7, y = 3.5}},
    {"grass-1", {x = -7, y = 4.5}},
    {"grass-1", {x = -6, y = -5.5}},
    {"grass-1", {x = -6, y = -4.5}},
    {"grass-1", {x = -6, y = -3.5}},
    {"grass-1", {x = -6, y = -2.5}},
    {"grass-1", {x = -6, y = -1.5}},
    {"grass-1", {x = -6, y = -0.5}},
    {"grass-1", {x = -6, y = 0.5}},
    {"grass-1", {x = -6, y = 1.5}},
    {"grass-1", {x = -6, y = 2.5}},
    {"grass-1", {x = -6, y = 3.5}},
    {"grass-1", {x = -6, y = 4.5}},
    {"grass-1", {x = -5, y = -5.5}},
    {"grass-1", {x = -5, y = -4.5}},
    {"grass-1", {x = -5, y = -3.5}},
    {"grass-1", {x = -5, y = -2.5}},
    {"grass-1", {x = -5, y = -1.5}},
    {"grass-1", {x = -5, y = -0.5}},
    {"grass-1", {x = -5, y = 0.5}},
    {"grass-1", {x = -5, y = 1.5}},
    {"grass-1", {x = -5, y = 2.5}},
    {"grass-1", {x = -5, y = 3.5}},
    {"grass-1", {x = -5, y = 4.5}},
    {"grass-1", {x = -4, y = -5.5}},
    {"grass-1", {x = -4, y = -4.5}},
    {"grass-1", {x = -4, y = -3.5}},
    {"grass-1", {x = -4, y = -2.5}},
    {"grass-1", {x = -4, y = -1.5}},
    {"grass-1", {x = -4, y = -0.5}},
    {"grass-1", {x = -4, y = 0.5}},
    {"grass-1", {x = -4, y = 1.5}},
    {"grass-1", {x = -4, y = 2.5}},
    {"grass-1", {x = -4, y = 3.5}},
    {"grass-1", {x = -4, y = 4.5}},
    {"grass-1", {x = -3, y = -5.5}},
    {"grass-1", {x = -3, y = -4.5}},
    {"grass-1", {x = -3, y = -3.5}},
    {"grass-1", {x = -3, y = -2.5}},
    {"grass-1", {x = -3, y = -1.5}},
    {"grass-1", {x = -3, y = -0.5}},
    {"grass-1", {x = -3, y = 0.5}},
    {"grass-1", {x = -3, y = 1.5}},
    {"grass-1", {x = -3, y = 2.5}},
    {"grass-1", {x = -3, y = 3.5}},
    {"grass-1", {x = -3, y = 4.5}},
    {"grass-1", {x = -2, y = -5.5}},
    {"grass-1", {x = -2, y = -4.5}},
    {"grass-1", {x = -2, y = -3.5}},
    {"grass-1", {x = -2, y = -2.5}},
    {"grass-1", {x = -2, y = -1.5}},
    {"grass-1", {x = -2, y = -0.5}},
    {"grass-1", {x = -2, y = 0.5}},
    {"grass-1", {x = -2, y = 1.5}},
    {"grass-1", {x = -2, y = 2.5}},
    {"grass-1", {x = -2, y = 3.5}},
    {"grass-1", {x = -2, y = 4.5}},
    {"grass-1", {x = -1, y = -5.5}},
    {"grass-1", {x = -1, y = -4.5}},
    {"grass-1", {x = -1, y = -3.5}},
    {"grass-1", {x = -1, y = -2.5}},
    {"grass-1", {x = -1, y = -1.5}},
    {"grass-1", {x = -1, y = -0.5}},
    {"grass-1", {x = -1, y = 0.5}},
    {"grass-1", {x = -1, y = 1.5}},
    {"grass-1", {x = -1, y = 2.5}},
    {"grass-1", {x = -1, y = 3.5}},
    {"grass-1", {x = -1, y = 4.5}},
    {"grass-1", {x = 0, y = -5.5}},
    {"grass-1", {x = 0, y = -4.5}},
    {"grass-1", {x = 0, y = -3.5}},
    {"grass-1", {x = 0, y = -2.5}},
    {"grass-1", {x = 0, y = -1.5}},
    {"grass-1", {x = 0, y = -0.5}},
    {"grass-1", {x = 0, y = 0.5}},
    {"grass-1", {x = 0, y = 1.5}},
    {"grass-1", {x = 0, y = 2.5}},
    {"grass-1", {x = 0, y = 3.5}},
    {"grass-1", {x = 0, y = 4.5}},
    {"grass-1", {x = 1, y = -5.5}},
    {"grass-1", {x = 1, y = -4.5}},
    {"grass-1", {x = 1, y = -3.5}},
    {"grass-1", {x = 1, y = -2.5}},
    {"grass-1", {x = 1, y = -1.5}},
    {"grass-1", {x = 1, y = -0.5}},
    {"grass-1", {x = 1, y = 0.5}},
    {"grass-1", {x = 1, y = 1.5}},
    {"grass-1", {x = 1, y = 2.5}},
    {"grass-1", {x = 1, y = 3.5}},
    {"grass-1", {x = 1, y = 4.5}},
    {"grass-1", {x = 2, y = -5.5}},
    {"grass-1", {x = 2, y = -4.5}},
    {"grass-1", {x = 2, y = -3.5}},
    {"grass-1", {x = 2, y = -2.5}},
    {"grass-1", {x = 2, y = -1.5}},
    {"grass-1", {x = 2, y = -0.5}},
    {"grass-1", {x = 2, y = 0.5}},
    {"grass-1", {x = 2, y = 1.5}},
    {"grass-1", {x = 2, y = 2.5}},
    {"grass-1", {x = 2, y = 3.5}},
    {"grass-1", {x = 2, y = 4.5}},
    {"grass-1", {x = 3, y = -5.5}},
    {"grass-1", {x = 3, y = -4.5}},
    {"grass-1", {x = 3, y = -3.5}},
    {"grass-1", {x = 3, y = -2.5}},
    {"grass-1", {x = 3, y = -1.5}},
    {"grass-1", {x = 3, y = -0.5}},
    {"grass-1", {x = 3, y = 0.5}},
    {"grass-1", {x = 3, y = 1.5}},
    {"grass-1", {x = 3, y = 2.5}},
    {"grass-1", {x = 3, y = 3.5}},
    {"grass-1", {x = 3, y = 4.5}},
    {"grass-1", {x = 4, y = -5.5}},
    {"grass-1", {x = 4, y = -4.5}},
    {"grass-1", {x = 4, y = -3.5}},
    {"grass-1", {x = 4, y = -2.5}},
    {"grass-1", {x = 4, y = -1.5}},
    {"grass-1", {x = 4, y = -0.5}},
    {"grass-1", {x = 4, y = 0.5}},
    {"grass-1", {x = 4, y = 1.5}},
    {"grass-1", {x = 4, y = 2.5}},
    {"grass-1", {x = 4, y = 3.5}},
    {"grass-1", {x = 4, y = 4.5}},
    {"grass-1", {x = 5, y = -5.5}},
    {"grass-1", {x = 5, y = -4.5}},
    {"grass-1", {x = 5, y = -3.5}},
    {"grass-1", {x = 5, y = -2.5}},
    {"grass-1", {x = 5, y = -1.5}},
    {"grass-1", {x = 5, y = -0.5}},
    {"grass-1", {x = 5, y = 0.5}},
    {"grass-1", {x = 5, y = 1.5}},
    {"grass-1", {x = 5, y = 2.5}},
    {"grass-1", {x = 5, y = 3.5}},
    {"grass-1", {x = 5, y = 4.5}},
    {"grass-1", {x = 6, y = -5.5}},
    {"grass-1", {x = 6, y = -4.5}},
    {"grass-1", {x = 6, y = -3.5}},
    {"grass-1", {x = 6, y = -2.5}},
    {"grass-1", {x = 6, y = -1.5}},
    {"grass-1", {x = 6, y = -0.5}},
    {"grass-1", {x = 6, y = 0.5}},
    {"grass-1", {x = 6, y = 1.5}},
    {"grass-1", {x = 6, y = 2.5}},
    {"grass-1", {x = 6, y = 3.5}},
    {"grass-1", {x = 6, y = 4.5}},
  }
}
